


INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Santiago');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Cerrillos',);
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Pudahuel');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Maipú');



INSERT INTO ROLES(NOMBRE) VALUES('Usuario');
INSERT INTO ROLES(NOMBRE) VALUES('Ejecutivo');
INSERT INTO ROLES(NOMBRE) VALUES('Administrador');



INSERT INTO ESTADO (NOMBRE) VALUES('Habilitado');
INSERT INTO ESTADO (NOMBRE) VALUES('Deshabilitado');



INSERT INTO USUARIOS(ID_ESTADO,RUT,NOMBRES,AP_PATERNO,AP_MATERNO,EMAIL,DIRECCION,CREATED_AT,ID_PERFIL,PASSWORD) VALUES (0,'182462756','RODRIGO','OTÁROLA','GUTIÉRREZ','rodrigo@mail.cl','catedral 1337',NOW(),3,'$2a$10$oeZlsckP/lGouIa3ROKP4.fr50ySvZL6uJ4ezpuILdQtVRyoKNJJG');
INSERT INTO USUARIOS(ID_ESTADO,RUT,NOMBRES,AP_PATERNO,AP_MATERNO,EMAIL,DIRECCION,CREATED_AT,ID_PERFIL,PASSWORD) VALUES (0,'253539992','SOFIA','OTÁROLA','BAÑARES','sofia@mail.cl','catedral 1337',NOW(),1,'$2a$10$oeZlsckP/lGouIa3ROKP4.fr50ySvZL6uJ4ezpuILdQtVRyoKNJJG');
INSERT INTO USUARIOS(ID_ESTADO,RUT,NOMBRES,AP_PATERNO,AP_MATERNO,EMAIL,DIRECCION,CREATED_AT,ID_PERFIL,PASSWORD) VALUES (0,'187290333','TANIA','BAÑARES','TORO','tania@mail.cl','catedral 1337',NOW(),2,'$2a$10$oeZlsckP/lGouIa3ROKP4.fr50ySvZL6uJ4ezpuILdQtVRyoKNJJG');