
#INSERTAMOS REGISTROS EN COMUNAS

INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Santiago');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES (0,'Cerrillos',);
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Pudahuel');
INSERT INTO COMUNAS (ID_ESTADO,NOMBRE)VALUES(0,'Maipú');

##INSERTAMOS ROLES

INSERT INTO ROLES(NOMBRE) VALUES('Usuario');
INSERT INTO ROLES(NOMBRE) VALUES('Ejecutivo');
INSERT INTO ROLES(NOMBRE) VALUES('Administrador');

#INSERTAMOS ESTADO

INSERT INTO ESTADO (NOMBRE) VALUES('Habilitado');
INSERT INTO ESTADO (NOMBRE) VALUES('Deshabilitado');

#INSERTAMOS USUARIOS

INSERT INTO USUARIOS(ID_ESTADO,RUT,NOMBRES,AP_PATERNO,AP_MATERNO,EMAIL,DIRECCION,CREATED_AT,ID_PERFIL) VALUES (0,'182462756','RODRIGO','OTÁROLA','GUTIÉRREZ','rodrigo@mail.cl','catedral 1337',NOW(),1);
INSERT INTO USUARIOS(ID_ESTADO,RUT,NOMBRES,AP_PATERNO,AP_MATERNO,EMAIL,DIRECCION,CREATED_AT,ID_PERFIL) VALUES (0,'253539992','SOFIA','OTÁROLA','BAÑARES','sofia@mail.cl','catedral 1337',NOW(),3);